#
# python trainer.py -c ./config/mppi_model_fnn_reward_fnn.yaml -p ./trained_model/
#

mpc:
    use_gpu:            1
    env_name:           GymPendulumEnv
    env_init_state:     [3.14159265354, 1]
    frame_skip:         4
    render:             True
    seed:               123

    mpc_method:         mppi
    num_rollouts:       100
    horizon:            15
    lambda:             1.0
    a_init:             [0.0]
    noise_sigma:        [1.0]

    max_frames:         6000
    max_epoch_steps:    500
    bootstrap_steps:    100
    retrain_steps:      50
    model_lr:           1e-3
    model_iter:         20
    batch_size:         250
    replay_buffer_size: 100000
    l1_norm:            False
    prune:              False

dynamics:
    type: fnn
    use_gpu: 1
    structure: [ 32, 32 ]
    activation: tanh
    std: 0.

value:
    type: fnn
    use_gpu: 1
    structure: [ 32, 32 ]
    activation: relu